### ISSUE TITLE
test-failure in stackage nightly build

### ISSUE THREAD

**Issue by bergmark** [visq/language-c#30]
It's not clear to me how serious this is so I'm marking the test suite as an expected failure for now, please let me know if we should keep it like that or if it can/will be fixed.

```
> /tmp/stackage-build14/language-c-0.6$ dist/build/language-c-harness/language-c-harness
Changing to test directory test/harness and compiling
make: *** No rule to make target 'prepare'.  Stop.
language-c-harness: callProcess: make "prepare" (exit 2): failed
```

**Comment by lambdageek** [comment]
@visq I think this is happening because `language-c.cabal` doesn't include any of the files under `test/harness/*` as extra-source-files.  So if you do `cabal get language-c` and then `ls test/harness` the only file that's shipped is `run-harness.hs`.

(Our `.travis.yml` doesn't test for that because it only does a `cabal install` from a source tarball, not a `cabal build && cabal test && cabal install`)

**Comment by visq** [comment]
@bergmark   
I see, thanks. We'll ensure the test works from the dist tarball and then I'll upload language-c 0.6.1 or 0.7.0.
@lambdageek
So extra-source-files should do the trick? It would be cool if travis.yml tested the dist tarball.

**Comment by visq** [comment]
@lambdageek 
Hmm, there is a lot that we would have to bundle for testing (examples, test framework, harness; I'm currently adding dg parse tests to the harness). I think it would be easier to disable the test if we are out of the source tree, and leave .travis.yml as is.

**Comment by lambdageek** [comment]
@visq I agree it's probably more expedient to have the harness disabled if running from a tarball - cabal doesn't make it easy to include a lot of extra source files, and while it would be nice to be able to test with a tarball, it would be a pain to maintain.
